### ISSUE TITLE
Using SharePoint Site instead of App Web

### ISSUE THREAD

**Issue by krusk** [jasonvenema/sharepoint-angular-peoplepicker#1]
Great directive. Is it possible to use the URL of a SharePoint Site instead of the App URL? Example, if I am creating a responsive Web design and want to use a SharePoint Site versus App Model.

Thanks,
K.

**Comment by jasonvenema** [comment]
The app web URL is used to get the SP.ClientContext object, which is required to match a partial user name against the list of all users. There is no reason why that shouldn't work for a standard SharePoint site URL.

Having said that, where you _might_ run into trouble is that an SP.ProxyWebRequestExecutorFactory is being attached to the client context to facilitate cross-domain calls from the browser. That's not typically necessary if you are not making cross-domain calls.

My suggestion would be to give it a try, and if it works, then great. If not, you may need to comment out the following lines in sp-peoplepicker.js:

``` javascript
var factory = new SP.ProxyWebRequestExecutorFactory($scope.appWebUrl);
$scope.spContext.set_webRequestExecutorFactory(factory);
```

Let me know how it turns out, and if you need to make any changes to the code to get it working, it may be worth committing those.

**Comment by krusk** [comment]
Commenting out that in the non-minified version did the trick! Do you know how/should I comment out the minified file. Or do you have a preferred JavaScript compressor?
